apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    cluster: prod-loc0003
    owner: platform-team
  name: hard-limit
  namespace: app-a
spec:
  hard:
    cpu: "1000"
    memory: 100Gi
    pods: "100"
