apiVersion: v1
kind: Service
metadata:
  labels:
    cluster: prod-loc0003
    env: canary
  name: nginx-service
  namespace: app-a
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    cluster: prod-loc0003
  type: LoadBalancer
