applySpecVersion: 1
spec:
  configSync:
    enabled: true
    sourceType: git
    sourceFormat: unstructured
    syncRepo: https://github.com/csantos/gkee-configsync-sample
    syncBranch: main
    syncRev: HEAD
    secretType: none
    policyDir: "configsync/clusters/prod-loc0003"
