apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-rs-embed
  namespace: config-management-system
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://github.com/csantos/gkee-configsync-sample
    revision: HEAD
    branch: main
    dir: configsync/clusters/prod-loc0002
    auth: none
    period: 45s
